### ISSUE TITLE
Attribut URL ignoriert "Leere Einträge verbergen"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_url#13]
da bei einer leeren URL-Eingabe in der Datenbank nicht "NULL" gespeichert wird, greift die Prüfung "Leere Einträge" nicht

siehe https://community.contao.org/de/showthread.php?61962-Attribut-URL-ignoriert-quot-Leere-Eintr%E4ge-verbergen-quot&p=404511

**Comment by discordier** [comment]
Array must get trimmed here: https://github.com/MetaModels/attribute_url/blob/ffe60c8e84c502c300cecb362fd018da521c43d6/src/MetaModels/Attribute/Url/Url.php#L67

**Comment by zonky2** [comment]
add PR: https://github.com/MetaModels/attribute_url/pull/14
